(() => {
'use strict';
const VERSION='0.4.0', SAVE_KEY='paws_plumes_traditional_v020', SETTINGS_KEY='paws_plumes_settings_v1';
const root=document.getElementById('gameRoot'), modalLayer=document.getElementById('modalLayer'), toastLayer=document.getElementById('toastLayer');
const APP={screen:'menu',save:loadSave(),settings:loadSettings(),selectedSlot:null,currentId:null,map:null,tiles:null,sprites:null,worldReady:false,raf:null,lastFrame:0,camera:{x:0,y:0},canvas:null,ctx:null,miniCanvas:null,keys:new Set(),moveTarget:null,pendingInteraction:null,selectedObjectId:null,panelTab:'inventory',installPrompt:null,swRegistration:null,combat:{enemyId:null,lastPlayerHit:0,lastEnemyHit:0,flourishReadyAt:0},motion:{actors:{},floaters:[],particles:[],chatter:null,nextChatter:0,lastStep:0,playerMoving:false,worldTime:0,lastClockMinute:-1,lastTimeSave:0},log:'Welcome to Port Felin.',create:{name:'',appearance:'orange',background:'duelist'}};
const APPEARANCES={orange:{label:'Orange Tabby',sprite:0,portrait:'assets/world/portrait_orange.png'},tuxedo:{label:'Tuxedo',sprite:1,portrait:'assets/world/portrait_tuxedo.png'},gray:{label:'Silver Gray',sprite:2,portrait:'assets/world/portrait_gray.png'}};
const BACKGROUNDS={
 duelist:{label:"Duelist's Page",desc:'Begins with stronger Fencing and a worn rapier.',bonuses:{fencing:1},items:{bread:2,healing_tonic:1},equipment:{weapon:'worn_rapier'}},
 artisan:{label:'Guild Artisan',desc:'Begins with stronger Smithing and useful materials.',bonuses:{smithing:1,crafting:1},items:{iron_ore:2,oak_log:2,bread:1},equipment:{weapon:'work_knife'}},
 mouser:{label:'Country Mouser',desc:'Begins with stronger Foraging and Woodcutting.',bonuses:{foraging:1,woodcutting:1},items:{rosemary:2,bread:3},equipment:{weapon:'hunting_knife'}}
};
const ITEMS={
 bread:{name:'Brown Bread',icon:'🥖',desc:'Restores 8 health.',value:3,use:'heal',amount:8},healing_tonic:{name:'Red Tonic',icon:'🧪',desc:'Restores 20 health.',value:12,use:'heal',amount:20},
 rosemary:{name:'Rosemary',icon:'🌿',desc:'Aromatic herb used by apothecaries.',value:2},reed:{name:'River Reed',icon:'🌾',desc:'Fiber for cord and baskets.',value:2},grape:{name:'Black Grape',icon:'🍇',desc:'Tart vineyard fruit.',value:2},oak_log:{name:'Oak Log',icon:'🪵',desc:'Stout crafting timber.',value:4},iron_ore:{name:'Iron Ore',icon:'⛏',desc:'Ore for smithing.',value:7},river_dace:{name:'Silver Dace',icon:'🐟',desc:'A small river fish. Better after a turn over the inn fire.',value:4},grilled_dace:{name:'Grilled Silver Dace',icon:'🍢',desc:'Hot river fish with herbs. Restores 14 health.',value:9,use:'heal',amount:14},
 worn_rapier:{name:'Worn Rapier',icon:'🗡',desc:'A serviceable old dueling blade.',attack:2,value:8},work_knife:{name:'Work Knife',icon:'🔪',desc:'A stout guild knife.',attack:1,value:6},hunting_knife:{name:'Hunting Knife',icon:'🔪',desc:'A light country blade.',attack:1,value:6},iron_rapier:{name:'Iron Rapier',icon:'⚔',desc:'A balanced Port Felin rapier.',attack:5,value:38},padded_doublet:{name:'Padded Doublet',icon:'🧥',desc:'Quilted protection under fine cloth.',defense:2,value:28}
};
const SKILL_NAMES={fencing:'Fencing',defense:'Defense',foraging:'Foraging',woodcutting:'Woodcutting',mining:'Mining',fishing:'Fishing',cooking:'Cooking',smithing:'Smithing',tailoring:'Tailoring',alchemy:'Alchemy',crafting:'Crafting'};
const QUESTS={first_commission:{title:'A Paw on the Roads',giver:'Guildmaster Luca',text:'Gather 3 rosemary and defeat 2 road bandits troubling the south road.',requirements:[['gathered','rosemary',3],['kills','bandit',2]],reward:{coins:45,xp:35,item:['healing_tonic',2]}},river_supper:{title:'A Proper Supper',giver:'Mina Whiskerpot',text:'Catch 3 Silver Dace from the river and cook 2 of them at the Warm Saucer.',requirements:[['gathered','river_dace',3],['crafted','grilled_dace',2]],reward:{coins:60,xp:45,item:['bread',2]},unlock:'first_commission'}};
const ENEMIES={bandit:{name:'Road Bandit',maxHp:24,attack:4,defense:1,xp:12,coins:[4,9],loot:[['bread',.35],['iron_ore',.12]]},boar:{name:'Bristleback',maxHp:34,attack:6,defense:2,xp:18,coins:[1,4],loot:[['bread',.45]]}};
const AUDIO_PATH='assets/audio/';
const AUDIO={ready:false,unlocked:false,music:null,ambience:null,zone:'town',sfx:{}};
const SFX_FILES=['ui_click','footstep','sword_hit','hurt','gather','coin','quest','level_up','fish_splash','cook_sizzle','loot_pickup'];
function loadSettings(){try{const raw=localStorage.getItem(SETTINGS_KEY),s=raw?JSON.parse(raw):{};return{music:clamp(Number(s.music??.34),0,1),ambience:clamp(Number(s.ambience??.32),0,1),sfx:clamp(Number(s.sfx??.62),0,1),mute:Boolean(s.mute)}}catch{return{music:.34,ambience:.32,sfx:.62,mute:false}}}
function persistSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(APP.settings))}catch{}applyAudioSettings()}
function initAudio(){if(AUDIO.ready)return;AUDIO.ready=true;AUDIO.music=new Audio(AUDIO_PATH+'music_port_felin.ogg');AUDIO.music.loop=true;AUDIO.music.preload='auto';AUDIO.ambience=new Audio(AUDIO_PATH+'ambience_town.ogg');AUDIO.ambience.loop=true;AUDIO.ambience.preload='auto';for(const n of SFX_FILES){const a=new Audio(AUDIO_PATH+n+'.ogg');a.preload='auto';AUDIO.sfx[n]=a}applyAudioSettings()}
function applyAudioSettings(){if(!AUDIO.ready)return;const muted=APP.settings.mute;AUDIO.music.volume=muted?0:APP.settings.music;AUDIO.ambience.volume=muted?0:APP.settings.ambience;updateAudioButton()}
function unlockAudio(){initAudio();if(AUDIO.unlocked)return;AUDIO.unlocked=true;AUDIO.music.play().catch(()=>{});AUDIO.ambience.play().catch(()=>{})}
function playSfx(name,scale=1){if(APP.settings.mute||APP.settings.sfx<=0)return;unlockAudio();const base=AUDIO.sfx[name];if(!base)return;const a=base.cloneNode();a.volume=clamp(APP.settings.sfx*scale,0,1);a.play().catch(()=>{})}
function updateAudioZone(){if(!AUDIO.unlocked||!current())return;const next=current().position.x<690?'town':'wild';if(next===AUDIO.zone)return;AUDIO.zone=next;const old=AUDIO.ambience;const replacement=new Audio(AUDIO_PATH+(next==='town'?'ambience_town.ogg':'ambience_wild.ogg'));replacement.loop=true;replacement.preload='auto';replacement.volume=APP.settings.mute?0:APP.settings.ambience;AUDIO.ambience=replacement;replacement.play().catch(()=>{});if(old){old.pause();old.currentTime=0}}
function toggleMute(){APP.settings.mute=!APP.settings.mute;persistSettings();if(!APP.settings.mute)unlockAudio();toast(APP.settings.mute?'Audio muted.':'Audio on.');updateAudioButton()}
function updateAudioButton(){const b=document.querySelector('[data-audio-toggle]');if(b){b.textContent=APP.settings.mute?'🔇':'🔊';b.title=APP.settings.mute?'Unmute audio':'Mute audio'}}
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
async function promptInstall(){if(!APP.installPrompt){toast(isStandalone()?'Already running as the installed app.':'Install prompt is not available in this browser right now.');return}const p=APP.installPrompt;APP.installPrompt=null;const result=await p.prompt();if(result?.outcome==='accepted')toast('Installing Paws & Plumes…');else toast('Installation cancelled.')}
async function checkForUpdate(){try{if(APP.swRegistration){await APP.swRegistration.update();toast('Checked for an app update.')}}catch{toast('Could not check for an update.')}}
async function refreshAppFiles(){if(!('caches'in window)){location.reload();return}try{for(const k of await caches.keys())if(k.startsWith('paws-plumes-'))await caches.delete(k);if(APP.swRegistration)await APP.swRegistration.update();toast('App files refreshed. Reloading…');setTimeout(()=>location.reload(),450)}catch{location.reload()}}
function installStatusText(){if(isStandalone())return'Installed — this window is running in standalone app mode.';if(APP.installPrompt)return'Ready to install on this device.';return'This browser is not offering a new install prompt. It may already have an older Paws & Plumes install registered, or it may require its browser menu to add the app.'}
function randomRange(a,b){return a+Math.random()*(b-a)}
function addFloater(x,y,text,color='#fff1bd'){APP.motion.floaters.push({x,y,text,color,life:1.05,max:1.05})}
function addBurst(x,y,color='#d8c17a',count=7){for(let i=0;i<count;i++)APP.motion.particles.push({x,y,vx:randomRange(-42,42),vy:randomRange(-58,-18),life:randomRange(.35,.75),max:.75,color,size:randomRange(2,4)})}
function blankSave(){return{version:VERSION,lastCharacterId:null,characters:[]}}
function loadSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return blankSave();const x=JSON.parse(raw);if(x&&Array.isArray(x.characters)){x.version=VERSION;return x}return blankSave()}catch{return blankSave()}}
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(APP.save))}catch{}}
function current(){return APP.save.characters.find(c=>c.id===APP.currentId)||null}
function makeId(){return'cat_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function dist(ax,ay,bx,by){return Math.hypot(ax-bx,ay-by)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function prop(o,n,f=null){const p=(o.properties||[]).find(x=>x.name===n);return p?p.value:f}
function xpNeed(l){return Math.floor(45*Math.pow(l,1.48))} function skillNeed(l){return Math.floor(26*Math.pow(l,1.55))}
function migrateCharacter(c){if(!c)return;c.quests=c.quests||{first_commission:'available'};if(!c.quests.first_commission)c.quests.first_commission='available';if(!c.quests.river_supper)c.quests.river_supper=c.quests.first_commission==='claimed'?'available':'locked';c.counters=c.counters||{};c.counters.kills=c.counters.kills||{};c.counters.gathered=c.counters.gathered||{};c.counters.crafted=c.counters.crafted||{};c.world=c.world||{};c.world.enemies=c.world.enemies||{};c.world.resources=c.world.resources||{};c.world.drops=Array.isArray(c.world.drops)?c.world.drops:[];if(!Number.isFinite(c.world.timeMinutes))c.world.timeMinutes=480;if(c.quests.first_commission==='claimed'&&c.quests.river_supper==='locked')c.quests.river_supper='available'}
function questState(id){const c=current(),q=QUESTS[id];if(!c||!q)return'locked';const st=c.quests[id];if(st)return st;if(q.unlock&&c.quests[q.unlock]!=='claimed')return'locked';return'available'}
function unlockQuests(){const c=current();if(!c)return;for(const[id,q]of Object.entries(QUESTS))if((c.quests[id]||'locked')==='locked'&&(!q.unlock||c.quests[q.unlock]==='claimed'))c.quests[id]='available'}
function acceptQuest(id){const c=current(),q=QUESTS[id];if(!c||!q||questState(id)!=='available')return;c.quests[id]='active';playSfx('quest',.7);saveCharacter();closeModal();toast(`Quest accepted: ${q.title}`);renderPanel()}
function formatWorldTime(){const c=current(),m=Math.floor(c?.world?.timeMinutes??480)%1440,h=Math.floor(m/60),mm=String(m%60).padStart(2,'0');return`${String(h).padStart(2,'0')}:${mm}`}
function nightLevel(){const h=((current()?.world?.timeMinutes??480)%1440)/60;if(h>=7&&h<18)return.02;if(h>=20||h<5)return.30;if(h>=18)return.02+(h-18)/2*.28;return.30-(h-5)/2*.28}
function updateWorldClock(){const e=document.getElementById('worldClock');if(e)e.textContent=formatWorldTime()}
function cleanupDrops(){const c=current();if(!c?.world?.drops)return;const now=Date.now(),before=c.world.drops.length;c.world.drops=c.world.drops.filter(d=>d.expiresAt>now);if(before!==c.world.drops.length&&String(APP.selectedObjectId||'').startsWith('drop_'))APP.selectedObjectId=null}
function spawnDrop(x,y,coins,items){if(!coins&&!Object.keys(items).length)return;const c=current();c.world.drops.push({id:'drop_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,5),type:'drop',name:'Loot',x,y,coins,items,expiresAt:Date.now()+120000})}
function dropSummary(d){const parts=[];if(d.coins)parts.push(`${d.coins} crowns`);for(const[k,n]of Object.entries(d.items||{}))parts.push(`${n} ${ITEMS[k]?.name||k}`);return parts.join(', ')||'nothing'}
function pickupDrop(d){const c=current();if(!c)return;c.coins+=d.coins||0;for(const[k,n]of Object.entries(d.items||{}))addItem(k,n);c.world.drops=c.world.drops.filter(x=>x.id!==d.id);APP.selectedObjectId=null;playSfx('loot_pickup',.85);if(d.coins)playSfx('coin',.35);APP.log=`Picked up ${dropSummary(d)}.`;toast(APP.log);addFloater(d.x,d.y-30,'Loot collected','#f6d66d');saveCharacter();renderPanel();updateHud()}
function npcQuestMarker(kind){const id=kind==='guildmaster'?'first_commission':kind==='innkeeper'?'river_supper':null;if(!id)return null;const st=questState(id);if(st==='available')return'!';if(st==='active'&&questProgress(id).complete)return'?';return null}
function drawQuestMarker(ctx,kind,x,y){const m=npcQuestMarker(kind);if(!m)return;ctx.save();ctx.beginPath();ctx.arc(x,y-58,10,0,Math.PI*2);ctx.fillStyle=m==='?'?'#77b997':'#d7b94e';ctx.fill();ctx.strokeStyle='#2b281f';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#1f241f';ctx.font='bold 14px Georgia';ctx.textAlign='center';ctx.fillText(m,x,y-53);ctx.restore()}
function cookFish(count=1){const n=Math.max(1,Math.min(count,countItem('river_dace')));if(n<1)return;if(countItem('river_dace')<n){toast('You need fresh Silver Dace.');return}removeItem('river_dace',n);addItem('grilled_dace',n);const c=current();c.counters.crafted.grilled_dace=(c.counters.crafted.grilled_dace||0)+n;addSkillXp('cooking',12*n);addPlayerXp(3*n);playSfx('cook_sizzle',.75);saveCharacter();closeModal();toast(`Cooked ${n} × Grilled Silver Dace.`);renderPanel()}
function createCharacter(name,appearance,background){const bg=BACKGROUNDS[background],skills={};Object.keys(SKILL_NAMES).forEach(k=>skills[k]={level:1,xp:0});for(const[k,v]of Object.entries(bg.bonuses||{}))skills[k].level+=v;return{id:makeId(),name:name.trim(),appearance,background,createdAt:Date.now(),lastPlayed:Date.now(),level:1,xp:0,hp:50,maxHp:50,coins:24,position:{x:346,y:670},inventory:{...bg.items},equipment:{weapon:bg.equipment.weapon,body:null},skills,quests:{first_commission:'available',river_supper:'locked'},counters:{kills:{bandit:0,boar:0},gathered:{},crafted:{}},world:{enemies:{},resources:{},drops:[],timeMinutes:480},discovered:{port_felin:true}}}
function saveCharacter(){const c=current();if(!c)return;c.lastPlayed=Date.now();APP.save.lastCharacterId=c.id;persist()}
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;toastLayer.appendChild(e);setTimeout(()=>e.remove(),2500)}
function closeModal(){modalLayer.classList.remove('open');modalLayer.innerHTML=''}
function modal(title,body){modalLayer.classList.add('open');modalLayer.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><header class="modal-head"><h2>${title}</h2><button class="close-btn" data-close>✕</button></header><div class="modal-body">${body}</div></section>`;modalLayer.querySelector('[data-close]').addEventListener('click',closeModal)}
function go(screen){if(APP.raf){cancelAnimationFrame(APP.raf);APP.raf=null}APP.keys.clear();APP.screen=screen;closeModal();if(screen==='menu')renderMenu();else if(screen==='select')renderCharacterSelect();else if(screen==='create')renderCharacterCreate();else if(screen==='game')renderGameShell()}
function renderMenu(){const last=APP.save.characters.find(c=>c.id===APP.save.lastCharacterId);root.innerHTML=`<section class="menu-screen"><div class="menu-wrap"><div class="menu-logo"><img src="assets/icons/icon-192.png" alt="Gilded Paw crest"><div class="menu-title"><span class="pre">A TALE OF THE GILDED PAW</span><h1>Paws &amp; Plumes</h1><p>A Renaissance fantasy adventure</p></div></div><div class="menu-actions"><button class="game-btn gold" data-menu="continue" ${last?'':'disabled'}>${last?`Continue — ${escapeHtml(last.name)}`:'Continue'}</button><button class="game-btn" data-menu="select">Characters</button><button class="game-btn teal" data-menu="new">New Character</button>${APP.installPrompt&&!isStandalone()?'<button class="game-btn gold" data-menu="install">Install App</button>':''}<button class="game-btn dark" data-menu="settings">Settings</button></div><div class="menu-version">v${VERSION} • traditional RPG prototype • saves remain on this device</div></div></section>`;root.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.menu;if(a==='continue'&&last)enterCharacter(last.id);else if(a==='select')go('select');else if(a==='new'){if(APP.save.characters.length>=3){toast('All three character slots are occupied.');go('select')}else{APP.selectedSlot=APP.save.characters.length;go('create')}}else if(a==='install')promptInstall();else if(a==='settings')openSettings()}))}
function relativeTime(t){const m=Math.max(0,Math.floor((Date.now()-t)/60000));if(m<1)return'just now';if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ago`;return`${Math.floor(h/24)}d ago`}
function renderCharacterSelect(){const cards=[0,1,2].map(slot=>{const c=APP.save.characters[slot];if(!c)return`<article class="character-card empty-slot"><div class="plus">+</div><div><h2>Empty Character Slot</h2><p>Create another adventurer in Port Felin.</p><button class="game-btn teal" data-new-slot="${slot}">Create Character</button></div></article>`;const total=Object.values(c.skills).reduce((s,v)=>s+v.level,0);return`<article class="character-card"><div class="character-portrait"><img src="${APPEARANCES[c.appearance].portrait}" alt="${escapeHtml(c.name)} portrait"></div><div class="character-info"><span class="tag">${escapeHtml(BACKGROUNDS[c.background].label)}</span><h2>${escapeHtml(c.name)}</h2><div class="char-stats"><span>Level ${c.level}</span><span>Total skill ${total}</span><span>◈ ${c.coins}</span></div><p class="muted small">Last played ${relativeTime(c.lastPlayed)}.</p><div class="character-actions"><button class="game-btn gold" data-play="${c.id}">Enter World</button><button class="game-btn ghost" data-delete="${c.id}" aria-label="Delete ${escapeHtml(c.name)}">✕</button></div></div></article>`}).join('');root.innerHTML=`<section class="parchment-screen"><div class="screen-shell"><header class="screen-head"><div><span class="caps">PORT FELIN REGISTRY</span><h1>Choose a Character</h1><p>Each character keeps separate skills, quests, equipment and world progress.</p></div><button class="game-btn dark" data-back>Back</button></header><div class="character-grid">${cards}</div></div></section>`;root.querySelector('[data-back]').addEventListener('click',()=>go('menu'));root.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',()=>enterCharacter(b.dataset.play)));root.querySelectorAll('[data-new-slot]').forEach(b=>b.addEventListener('click',()=>{APP.selectedSlot=Number(b.dataset.newSlot);go('create')}));root.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>confirmDelete(b.dataset.delete)))}
function renderCharacterCreate(){root.innerHTML=`<section class="parchment-screen"><div class="screen-shell"><header class="screen-head"><div><span class="caps">NEW ADVENTURER</span><h1>Create Character</h1><p>No fixed class. Your skills improve by using them.</p></div><button class="game-btn dark" data-back>Cancel</button></header><div class="create-layout"><div class="create-preview"><img id="createPortrait" src="${APPEARANCES[APP.create.appearance].portrait}" alt="Character preview"></div><form class="create-form" id="createForm"><div class="field"><label for="charName">Name</label><input id="charName" maxlength="18" autocomplete="off" placeholder="e.g. Belladonna" value="${escapeHtml(APP.create.name)}" required></div><div class="field"><label>Coat</label><div class="choice-row" id="appearanceChoices">${Object.entries(APPEARANCES).map(([k,v])=>`<button type="button" class="choice ${APP.create.appearance===k?'active':''}" data-appearance="${k}"><strong>${v.label}</strong><small>${k==='orange'?'Classic tabby':k==='tuxedo'?'Black & white':'Cool silver coat'}</small></button>`).join('')}</div></div><div class="field"><label>Upbringing</label><div class="choice-row" id="backgroundChoices">${Object.entries(BACKGROUNDS).map(([k,v])=>`<button type="button" class="choice ${APP.create.background===k?'active':''}" data-background="${k}"><strong>${v.label}</strong><small>${v.desc}</small></button>`).join('')}</div></div><div class="form-actions"><button class="game-btn gold" type="submit">Create & Enter World</button><button class="game-btn dark" type="button" data-back>Cancel</button></div></form></div></div></section>`;
 root.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>go('select')));root.querySelectorAll('[data-appearance]').forEach(b=>b.addEventListener('click',()=>{APP.create.appearance=b.dataset.appearance;document.getElementById('createPortrait').src=APPEARANCES[APP.create.appearance].portrait;root.querySelectorAll('[data-appearance]').forEach(x=>x.classList.toggle('active',x===b))}));root.querySelectorAll('[data-background]').forEach(b=>b.addEventListener('click',()=>{APP.create.background=b.dataset.background;root.querySelectorAll('[data-background]').forEach(x=>x.classList.toggle('active',x===b))}));document.getElementById('createForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('charName').value.trim();if(name.length<2){toast('Choose a name with at least two letters.');return}const c=createCharacter(name,APP.create.appearance,APP.create.background);const slot=APP.selectedSlot??APP.save.characters.length;APP.save.characters.splice(slot,0,c);APP.save.characters=APP.save.characters.slice(0,3);APP.save.lastCharacterId=c.id;persist();APP.create={name:'',appearance:'orange',background:'duelist'};enterCharacter(c.id)})}
function confirmDelete(cid){const c=APP.save.characters.find(x=>x.id===cid);if(!c)return;modal('Delete Character',`<p>Delete <strong>${escapeHtml(c.name)}</strong>? This removes that character's local progress.</p><div class="form-actions"><button class="game-btn danger" data-confirm-delete="${c.id}">Delete Permanently</button><button class="game-btn dark" data-close2>Cancel</button></div>`);modalLayer.querySelector('[data-confirm-delete]').addEventListener('click',()=>{APP.save.characters=APP.save.characters.filter(x=>x.id!==cid);if(APP.save.lastCharacterId===cid)APP.save.lastCharacterId=APP.save.characters[0]?.id||null;persist();closeModal();renderCharacterSelect()});modalLayer.querySelector('[data-close2]').addEventListener('click',closeModal)}
function openSettings(){const installText=installStatusText();modal('Settings',`<p>This remains a traditional RPG: touch changes the controls, not the progression model.</p><div class="settings-group"><h3>Audio</h3><label class="range-row">Music <input type="range" min="0" max="1" step="0.05" value="${APP.settings.music}" data-volume="music"></label><label class="range-row">Ambience <input type="range" min="0" max="1" step="0.05" value="${APP.settings.ambience}" data-volume="ambience"></label><label class="range-row">Effects <input type="range" min="0" max="1" step="0.05" value="${APP.settings.sfx}" data-volume="sfx"></label><button class="game-btn dark" data-mute>${APP.settings.mute?'Unmute Audio':'Mute Audio'}</button></div><div class="settings-group install-box"><h3>Install / Update</h3><p id="installStatus">${installText}</p><div class="form-actions">${APP.installPrompt&&!isStandalone()?'<button class="game-btn gold" data-install>Install App</button>':''}<button class="game-btn teal" data-update>Check for Update</button><button class="game-btn dark" data-refresh-app>Refresh App Files</button></div><p class="small muted">v${VERSION} uses a new explicit PWA identity so early prototype installs do not block this RPG build.</p></div><div class="settings-group"><button class="game-btn danger" data-reset-all>Erase All Local Characters</button></div>`);modalLayer.querySelectorAll('[data-volume]').forEach(i=>i.addEventListener('input',()=>{APP.settings[i.dataset.volume]=Number(i.value);persistSettings();if(!APP.settings.mute)unlockAudio()}));modalLayer.querySelector('[data-mute]').addEventListener('click',()=>{toggleMute();closeModal();openSettings()});const install=modalLayer.querySelector('[data-install]');if(install)install.addEventListener('click',promptInstall);modalLayer.querySelector('[data-update]').addEventListener('click',checkForUpdate);modalLayer.querySelector('[data-refresh-app]').addEventListener('click',refreshAppFiles);modalLayer.querySelector('[data-reset-all]').addEventListener('click',()=>{if(confirm('Erase every Paws & Plumes character on this device?')){APP.save=blankSave();persist();closeModal();go('menu')}})}
function enterCharacter(cid){APP.currentId=cid;const c=current();if(!c){go('select');return}migrateCharacter(c);c.lastPlayed=Date.now();APP.save.lastCharacterId=cid;persist();APP.moveTarget=null;APP.pendingInteraction=null;APP.selectedObjectId=null;APP.combat={enemyId:null,lastPlayerHit:0,lastEnemyHit:0,flourishReadyAt:0};go('game')}
function renderGameShell(){const c=current();root.innerHTML=`<section class="play-screen"><header class="hud-top"><div class="hud-portrait"><img src="${APPEARANCES[c.appearance].portrait}" alt=""></div><div><div class="hud-name"><strong>${escapeHtml(c.name)}</strong><span class="hud-level">Lv ${c.level}</span></div><div class="bars"><div class="bar hp"><span id="hpBar"></span></div><div class="bar xp"><span id="xpBar"></span></div></div></div><div class="hud-money"><div>◈ <span id="coinCount">${c.coins}</span> <span class="coins-word">crowns</span></div><span class="hud-clock" id="worldClock">${formatWorldTime()}</span></div></header><div class="world-layout"><div class="world-wrap" id="worldWrap"><canvas id="worldCanvas" tabindex="0" aria-label="Port Felin game world"></canvas><div class="world-label"><strong>Port Felin & South Road</strong><span>Fish the river • dropped loot remains in the world</span></div><div class="target-float" id="targetFloat"><strong id="targetName"></strong><div class="target-bar"><span id="targetHp"></span></div></div></div><aside class="side-panel" id="sidePanel"><div class="mini-map"><canvas id="miniCanvas"></canvas></div><div class="panel-tabs"><button class="panel-tab active" data-tab="inventory" title="Inventory">🎒</button><button class="panel-tab" data-tab="skills" title="Skills">✦</button><button class="panel-tab" data-tab="quests" title="Quests">📜</button><button class="panel-tab" data-tab="equipment" title="Equipment">⚔</button></div><div class="panel-body" id="panelBody"></div></aside></div><footer class="bottom-bar"><button class="utility-btn mobile-panel-btn" id="mobilePanelBtn" aria-label="Open character panel">☰</button><div class="combat-log" id="combatLog">${escapeHtml(APP.log)}</div><div class="hotbar"><button class="hotkey active" data-hot="attack"><span>1</span>⚔</button><button class="hotkey" data-hot="flourish"><span>2</span>✦</button><button class="hotkey" data-hot="tonic"><span>3</span>🧪</button><button class="hotkey" data-hot="bread"><span>4</span>🥖</button><button class="hotkey" data-hot="interact"><span>5</span>☝</button></div><div class="utility-btns"><button class="utility-btn" data-audio-toggle title="Mute audio">🔊</button><button class="utility-btn" data-menu-game title="Game menu">☰</button></div></footer></section>`;APP.canvas=document.getElementById('worldCanvas');APP.ctx=APP.canvas.getContext('2d');APP.miniCanvas=document.getElementById('miniCanvas');bindGameUI();updateHud();updateAudioButton();renderPanel();loadWorld()}
function bindGameUI(){const canvas=APP.canvas;canvas.addEventListener('pointerup',worldPointer);canvas.addEventListener('contextmenu',e=>e.preventDefault());document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{APP.panelTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderPanel()}));document.getElementById('mobilePanelBtn').addEventListener('click',()=>{const panel=document.getElementById('sidePanel');panel.classList.toggle('mobile-open');requestAnimationFrame(()=>{resizeWorld();drawMiniMap()})});document.querySelector('[data-menu-game]').addEventListener('click',openGameMenu);document.querySelector('[data-audio-toggle]').addEventListener('click',toggleMute);document.querySelectorAll('[data-hot]').forEach(b=>b.addEventListener('click',()=>useHotbar(b.dataset.hot)));window.addEventListener('resize',resizeWorld,{once:true});}
async function loadWorld(){try{const [map,tiles,sprites]=await Promise.all([fetch('assets/maps/port_felin_world.json').then(r=>r.json()),loadImage('assets/world/world_tiles.png'),loadImage('assets/world/cat_sprites.png')]);APP.map=map;APP.tiles=tiles;APP.sprites=sprites;APP.worldReady=true;initializeWorldState();resizeWorld();APP.lastFrame=performance.now();APP.raf=requestAnimationFrame(loop)}catch(e){console.error(e);toast('Could not load the world map.');}}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
function initializeWorldState(){const c=current();migrateCharacter(c);cleanupDrops();const objs=worldObjects();APP.motion.actors={};APP.motion.civilians=[{x:92,y:435,sprite:1},{x:95,y:650,sprite:2},{x:348,y:535,sprite:0},{x:565,y:520,sprite:2},{x:565,y:705,sprite:1},{x:335,y:775,sprite:4}].map((v,i)=>({...v,homeX:v.x,homeY:v.y,targetX:v.x,targetY:v.y,nextMove:performance.now()+randomRange(400,2500),speed:18+Math.random()*8,id:'civilian_'+i}));APP.motion.floaters=[];APP.motion.particles=[];APP.motion.chatter=null;APP.motion.nextChatter=performance.now()+randomRange(3500,6500);APP.motion.lastClockMinute=-1;APP.motion.lastTimeSave=performance.now();for(const o of objs){const ctr={x:o.x+(o.width||0)/2,y:o.y+(o.height||0)/2};if(o.type==='enemy'){const kind=prop(o,'enemy');if(!c.world.enemies[o.id])c.world.enemies[o.id]={hp:ENEMIES[kind].maxHp,alive:true,respawnAt:0};APP.motion.actors[o.id]={x:ctr.x,y:ctr.y,homeX:ctr.x,homeY:ctr.y,targetX:ctr.x,targetY:ctr.y,nextMove:0,speed:kind==='boar'?52:43,kind:'enemy'}}else if(o.type==='npc'){APP.motion.actors[o.id]={x:ctr.x,y:ctr.y,homeX:ctr.x,homeY:ctr.y,targetX:ctr.x,targetY:ctr.y,nextMove:performance.now()+randomRange(500,2800),speed:22+Math.random()*9,kind:'npc'}}else if(o.type==='resource'&&!c.world.resources[o.id])c.world.resources[o.id]={readyAt:0}}for(let i=0;i<24;i++)APP.motion.particles.push({ambient:true,x:Math.random()*APP.map.width*64,y:Math.random()*APP.map.height*64,vx:randomRange(3,9),vy:randomRange(-2,2),life:999,max:999,color:'rgba(244,222,160,.20)',size:randomRange(1,2.7)});saveCharacter()}
function worldObjects(){return APP.map?.layers.find(l=>l.name==='World Objects')?.objects||[]}
function resizeWorld(){if(APP.screen!=='game'||!APP.canvas)return;const wrap=document.getElementById('worldWrap');if(!wrap)return;const r=wrap.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);APP.canvas.width=Math.max(1,Math.floor(r.width*dpr));APP.canvas.height=Math.max(1,Math.floor(r.height*dpr));APP.canvas._cssW=r.width;APP.canvas._cssH=r.height;APP.canvas._dpr=dpr;const mr=APP.miniCanvas.getBoundingClientRect();APP.miniCanvas.width=Math.max(1,Math.floor(mr.width*dpr));APP.miniCanvas.height=Math.max(1,Math.floor(mr.height*dpr));drawMiniMap()}
function loop(now){if(APP.screen!=='game')return;const dt=Math.min(.05,(now-APP.lastFrame)/1000||0);APP.lastFrame=now;updateWorld(dt,now);drawWorld();APP.raf=requestAnimationFrame(loop)}
function updateWorld(dt,now){const c=current();if(!c)return;APP.motion.worldTime+=dt;c.world.timeMinutes=(c.world.timeMinutes+dt*2)%1440;const minute=Math.floor(c.world.timeMinutes);if(minute!==APP.motion.lastClockMinute){APP.motion.lastClockMinute=minute;updateWorldClock()}if(now-APP.motion.lastTimeSave>10000){APP.motion.lastTimeSave=now;saveCharacter()}cleanupDrops();APP.motion.playerMoving=false;let dx=0,dy=0;if(APP.keys.has('w')||APP.keys.has('arrowup'))dy-=1;if(APP.keys.has('s')||APP.keys.has('arrowdown'))dy+=1;if(APP.keys.has('a')||APP.keys.has('arrowleft'))dx-=1;if(APP.keys.has('d')||APP.keys.has('arrowright'))dx+=1;if(dx||dy){APP.moveTarget=null;APP.pendingInteraction=null;const mag=Math.hypot(dx,dy);movePlayer(dx/mag*165*dt,dy/mag*165*dt)}else if(APP.moveTarget){const d=dist(c.position.x,c.position.y,APP.moveTarget.x,APP.moveTarget.y);if(d<5){APP.moveTarget=null}else{const step=Math.min(d,165*dt);movePlayer((APP.moveTarget.x-c.position.x)/d*step,(APP.moveTarget.y-c.position.y)/d*step)}}if(APP.motion.playerMoving&&now-APP.motion.lastStep>390){APP.motion.lastStep=now;playSfx('footstep',.34)}updateActors(dt,now);updateEffects(dt);if(APP.pendingInteraction){const o=objectById(APP.pendingInteraction);if(o){const ctr=objectCenter(o);if(dist(c.position.x,c.position.y,ctr.x,ctr.y)<110){const oid=APP.pendingInteraction;APP.pendingInteraction=null;APP.moveTarget=null;interactObject(objectById(oid))}}}updateEnemyRespawns(now);updateCombat(now);updateAudioZone();updateCamera();}
function movePlayer(dx,dy){const c=current(),nx=clamp(c.position.x+dx,24,APP.map.width*64-24),ny=clamp(c.position.y+dy,24,APP.map.height*64-24);if(isWalkable(nx,ny)&&!hitsBuilding(nx,ny)){if(Math.abs(nx-c.position.x)+Math.abs(ny-c.position.y)>.05)APP.motion.playerMoving=true;c.position.x=nx;c.position.y=ny;saveCharacterThrottled()}}
function isWalkable(x,y){const tx=clamp(Math.floor(x/64),0,APP.map.width-1),ty=clamp(Math.floor(y/64),0,APP.map.height-1);const ground=APP.map.layers.find(l=>l.name==='Ground');const gid=ground.data[ty*APP.map.width+tx];return gid!==3&&gid!==6}
function hitsBuilding(x,y){return worldObjects().some(o=>o.type==='building'&&x>o.x-12&&x<o.x+o.width+12&&y>o.y-16&&y<o.y+o.height+18)}
function chooseWanderTarget(m,radius){for(let tries=0;tries<8;tries++){const ang=Math.random()*Math.PI*2,rad=Math.random()*radius,nx=m.homeX+Math.cos(ang)*rad,ny=m.homeY+Math.sin(ang)*rad;if(isWalkable(nx,ny)&&!hitsBuilding(nx,ny)){m.targetX=nx;m.targetY=ny;return}}m.targetX=m.homeX;m.targetY=m.homeY}
function moveActor(m,tx,ty,speed,dt){const d=dist(m.x,m.y,tx,ty);if(d<1)return;const step=Math.min(d,speed*dt),nx=m.x+(tx-m.x)/d*step,ny=m.y+(ty-m.y)/d*step;if(isWalkable(nx,ny)&&!hitsBuilding(nx,ny)){m.x=nx;m.y=ny}else{m.targetX=m.homeX;m.targetY=m.homeY}}
function updateActors(dt,now){const c=current();if(!c)return;for(const o of worldObjects()){const m=APP.motion.actors[o.id];if(!m)continue;if(o.type==='npc'){if(now>=m.nextMove||dist(m.x,m.y,m.targetX,m.targetY)<4){chooseWanderTarget(m,36);m.nextMove=now+randomRange(2400,5600)}moveActor(m,m.targetX,m.targetY,m.speed,dt)}else if(o.type==='enemy'){const ws=c.world.enemies[o.id];if(!ws?.alive){m.x=m.homeX;m.y=m.homeY;continue}const aggro=prop(o,'enemy')==='boar'?145:175,d=dist(m.x,m.y,c.position.x,c.position.y),homeD=dist(m.x,m.y,m.homeX,m.homeY);if(d<aggro||APP.combat.enemyId===o.id){moveActor(m,c.position.x,c.position.y,m.speed+(APP.combat.enemyId===o.id?14:0),dt);if(d<70&&!APP.combat.enemyId){APP.combat.enemyId=o.id;APP.selectedObjectId=o.id;APP.log=`${o.name} closes in!`;updateHud()}}else if(homeD>92){moveActor(m,m.homeX,m.homeY,m.speed,dt)}else{if(now>=m.nextMove||dist(m.x,m.y,m.targetX,m.targetY)<4){chooseWanderTarget(m,68);m.nextMove=now+randomRange(1800,4200)}moveActor(m,m.targetX,m.targetY,m.speed*.6,dt)}}}for(const m of APP.motion.civilians||[]){if(now>=m.nextMove||dist(m.x,m.y,m.targetX,m.targetY)<4){chooseWanderTarget(m,52);m.nextMove=now+randomRange(2200,5600)}moveActor(m,m.targetX,m.targetY,m.speed,dt)}if(now>APP.motion.nextChatter){const npcs=worldObjects().filter(o=>o.type==='npc');if(npcs.length){const o=npcs[Math.floor(Math.random()*npcs.length)],lines=['Fine weather for a walk.','Mind the south road.','Fresh fish at the quay!','The guild always has work.','I heard bells by the bridge.','A good coat deserves a good hat.'];APP.motion.chatter={id:o.id,text:lines[Math.floor(Math.random()*lines.length)],until:now+2600}}APP.motion.nextChatter=now+randomRange(7000,12000)}}
function updateEffects(dt){for(const f of APP.motion.floaters){f.life-=dt;f.y-=26*dt}APP.motion.floaters=APP.motion.floaters.filter(f=>f.life>0);for(const p of APP.motion.particles){if(p.ambient){p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x>APP.map.width*64+20)p.x=-20;continue}p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=72*dt}APP.motion.particles=APP.motion.particles.filter(p=>p.ambient||p.life>0)}
function drawCloudShadows(ctx){const w=APP.map.width*64,t=APP.motion.worldTime;ctx.save();ctx.globalAlpha=.065;ctx.fillStyle='#233a35';for(let i=0;i<4;i++){const x=((t*18+i*430)%(w+500))-250,y=120+i*210;ctx.beginPath();ctx.ellipse(x,y,150,48,.12,0,Math.PI*2);ctx.ellipse(x+110,y+20,115,38,-.1,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawAmbientParticles(ctx){for(const p of APP.motion.particles){if(!p.ambient)continue;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}}
function drawEffects(ctx){for(const p of APP.motion.particles){if(p.ambient)continue;ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font='bold 14px Georgia';for(const f of APP.motion.floaters){ctx.globalAlpha=clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1}
function drawSpeech(ctx,text,x,y){ctx.save();ctx.font='11px system-ui,sans-serif';const w=Math.min(150,ctx.measureText(text).width+16);ctx.fillStyle='rgba(246,236,204,.94)';ctx.strokeStyle='rgba(55,47,37,.85)';ctx.lineWidth=1;ctx.fillRect(x-w/2,y-18,w,20);ctx.strokeRect(x-w/2,y-18,w,20);ctx.fillStyle='#342d25';ctx.textAlign='center';ctx.fillText(text,x,y-4);ctx.restore()}
function drawLightTint(ctx,w,h){const alpha=nightLevel();if(alpha<=.025)return;ctx.save();ctx.fillStyle=`rgba(18,29,49,${alpha})`;ctx.fillRect(0,0,w,h);ctx.restore()}
let saveTimer=0;function saveCharacterThrottled(){const n=Date.now();if(n-saveTimer>700){saveTimer=n;saveCharacter()}}
function updateCamera(){const c=current(),cw=APP.canvas._cssW||800,ch=APP.canvas._cssH||600,worldW=APP.map.width*64,worldH=APP.map.height*64;APP.camera.x=clamp(c.position.x-cw/2,0,Math.max(0,worldW-cw));APP.camera.y=clamp(c.position.y-ch/2,0,Math.max(0,worldH-ch))}
function drawWorld(){if(!APP.worldReady||!APP.ctx)return;const ctx=APP.ctx,dpr=APP.canvas._dpr||1,cw=APP.canvas._cssW||APP.canvas.width,ch=APP.canvas._cssH||APP.canvas.height;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cw,ch);ctx.save();ctx.translate(-APP.camera.x,-APP.camera.y);drawTiles(ctx);drawCloudShadows(ctx);drawBuildings(ctx);drawAmbientParticles(ctx);drawWorldObjects(ctx);drawPlayer(ctx);drawEffects(ctx);ctx.restore();drawLightTint(ctx,cw,ch);drawTargetUI();drawMiniMap()}
function drawTiles(ctx){const ground=APP.map.layers.find(l=>l.name==='Ground'),tile=64,startX=Math.max(0,Math.floor(APP.camera.x/tile)-1),endX=Math.min(APP.map.width,Math.ceil((APP.camera.x+(APP.canvas._cssW||800))/tile)+1),startY=Math.max(0,Math.floor(APP.camera.y/tile)-1),endY=Math.min(APP.map.height,Math.ceil((APP.camera.y+(APP.canvas._cssH||600))/tile)+1);ctx.imageSmoothingEnabled=false;for(let y=startY;y<endY;y++)for(let x=startX;x<endX;x++){const gid=ground.data[y*APP.map.width+x];if(gid)ctx.drawImage(APP.tiles,(gid-1)*64,0,64,64,x*64,y*64,64,64)}}
function drawBuildings(ctx){const dark=nightLevel();for(const o of worldObjects().filter(x=>x.type==='building')){ctx.fillStyle='#6d4a35';ctx.strokeStyle='#2a2420';ctx.lineWidth=4;ctx.fillRect(o.x,o.y,o.width,o.height);ctx.strokeRect(o.x,o.y,o.width,o.height);ctx.fillStyle='#884c39';ctx.beginPath();ctx.moveTo(o.x-8,o.y);ctx.lineTo(o.x+o.width/2,o.y-38);ctx.lineTo(o.x+o.width+8,o.y);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#d3b567';ctx.fillRect(o.x+o.width*.42,o.y+o.height-38,o.width*.16,38);const wy=o.y+o.height*.46;for(const wx of[o.x+o.width*.23,o.x+o.width*.77]){if(dark>.07){const g=ctx.createRadialGradient(wx,wy,2,wx,wy,28);g.addColorStop(0,`rgba(255,210,99,${Math.min(.42,dark*1.5)})`);g.addColorStop(1,'rgba(255,210,99,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(wx,wy,28,0,Math.PI*2);ctx.fill()}ctx.fillStyle=dark>.07?'#e4b85e':'#7e8e83';ctx.fillRect(wx-8,wy-7,16,14);ctx.strokeStyle='#382f28';ctx.lineWidth=2;ctx.strokeRect(wx-8,wy-7,16,14)}ctx.fillStyle='#f0dfad';ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(o.name,o.x+o.width/2,o.y+o.height+17)}}
function drawWorldObjects(ctx){const c=current(),now=Date.now(),t=APP.motion.worldTime;for(const o of worldObjects()){if(o.type==='spawn'||o.type==='building')continue;const ctr=objectCenter(o),selected=String(APP.selectedObjectId)===String(o.id);if(o.type==='enemy'){const ws=c.world.enemies[o.id];if(!ws?.alive)continue;const sprite=Number(prop(o,'sprite',5)),bob=Math.sin(t*6+o.id)*1.4;drawSprite(ctx,sprite,ctr.x,ctr.y+bob);drawName(ctx,o.name,ctr.x,ctr.y-40+bob,selected);if(ws.hp<ENEMIES[prop(o,'enemy')].maxHp)drawSmallHp(ctx,ctr.x,ctr.y-31+bob,ws.hp/ENEMIES[prop(o,'enemy')].maxHp)}else if(o.type==='npc'){const bob=Math.sin(t*2.5+o.id)*1.1,kind=prop(o,'kind');drawSprite(ctx,Number(prop(o,'sprite',3)),ctr.x,ctr.y+bob);drawName(ctx,o.name,ctr.x,ctr.y-40+bob,selected);drawQuestMarker(ctx,kind,ctr.x,ctr.y+bob);if(APP.motion.chatter?.id===o.id&&APP.motion.chatter.until>performance.now())drawSpeech(ctx,APP.motion.chatter.text,ctr.x,ctr.y-58)}else if(o.type==='resource'){const rs=c.world.resources[o.id],ready=!rs||rs.readyAt<=now,sway=Math.sin(t*2+o.id)*3;drawResource(ctx,prop(o,'resource'),ctr.x+sway,ctr.y,ready,selected);drawName(ctx,o.name,ctr.x,ctr.y-31,selected)}else if(o.type==='landmark'){ctx.fillStyle='#d5bf72';ctx.font='28px Georgia';ctx.textAlign='center';ctx.fillText('⌘',ctr.x,ctr.y);drawName(ctx,o.name,ctr.x,ctr.y-26,selected)}}for(const d of c.world.drops){const bob=Math.sin(t*5+d.x*.01)*2,selected=APP.selectedObjectId===d.id;ctx.save();ctx.translate(d.x,d.y+bob);ctx.fillStyle=selected?'#f0cb63':'#b99448';ctx.strokeStyle='#30271d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-4,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#efe0a2';ctx.font='bold 13px Georgia';ctx.textAlign='center';ctx.fillText('✦',0,1);ctx.restore();if(selected)drawName(ctx,'Loot',d.x,d.y-24+bob,true)}for(const m of APP.motion.civilians||[]){const bob=Math.sin(t*3+Number(String(m.id).split('_').pop()))*.8;ctx.save();ctx.globalAlpha=.92;drawSprite(ctx,m.sprite,m.x,m.y+bob);ctx.restore()}}
function drawSprite(ctx,index,x,y){ctx.drawImage(APP.sprites,index*64,0,64,64,x-32,y-50,64,64)}
function drawPlayer(ctx){const c=current(),idx=APPEARANCES[c.appearance].sprite,bob=APP.motion.playerMoving?Math.sin(APP.motion.worldTime*14)*2.2:Math.sin(APP.motion.worldTime*2.6)*.7;ctx.save();ctx.shadowColor='rgba(0,0,0,.38)';ctx.shadowBlur=4;ctx.shadowOffsetY=4;drawSprite(ctx,idx,c.position.x,c.position.y+bob);ctx.restore();ctx.fillStyle='#fff1bd';ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(c.name,c.position.x,c.position.y-43+bob)}
function drawName(ctx,name,x,y,selected){ctx.font='bold 11px Georgia';ctx.textAlign='center';const w=ctx.measureText(name).width+12;ctx.fillStyle=selected?'rgba(116,58,61,.94)':'rgba(24,30,27,.78)';ctx.fillRect(x-w/2,y-11,w,16);ctx.fillStyle='#f1e5c6';ctx.fillText(name,x,y+1)}
function drawSmallHp(ctx,x,y,p){ctx.fillStyle='#1c1816';ctx.fillRect(x-22,y,44,5);ctx.fillStyle='#a34a46';ctx.fillRect(x-21,y+1,42*clamp(p,0,1),3)}
function drawResource(ctx,type,x,y,ready,selected){ctx.globalAlpha=ready?1:.38;ctx.font=selected?'31px serif':'27px serif';ctx.textAlign='center';const icons={rosemary:'🌿',reed:'🌾',grape:'🍇',oak_log:'🌳',iron_ore:'⛏',river_dace:'🐟'};ctx.fillText(icons[type]||'✦',x,y);ctx.globalAlpha=1}
function objectCenter(o){if(o?.type==='drop')return{x:o.x,y:o.y};const m=APP.motion.actors[o.id];if(m&&(o.type==='npc'||o.type==='enemy'))return{x:m.x,y:m.y};return{x:o.x+(o.width||0)/2,y:o.y+(o.height||0)/2}}
function objectById(id){return worldObjects().find(o=>String(o.id)===String(id))||current()?.world?.drops?.find(d=>String(d.id)===String(id))||null}
function drawMiniMap(){if(!APP.map||!APP.miniCanvas)return;const ctx=APP.miniCanvas.getContext('2d'),w=APP.miniCanvas.width,h=APP.miniCanvas.height,dpr=Math.min(window.devicePixelRatio||1,2);ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,w,h);const sx=w/(APP.map.width*64),sy=h/(APP.map.height*64),ground=APP.map.layers.find(l=>l.name==='Ground'),colors=['','#71885b','#9d9078','#5f8f93','#a48661','#9a8a4c','#40553d'];for(let y=0;y<APP.map.height;y++)for(let x=0;x<APP.map.width;x++){ctx.fillStyle=colors[ground.data[y*APP.map.width+x]]||'#777';ctx.fillRect(x*64*sx,y*64*sy,64*sx+1,64*sy+1)}const c=current();for(const o of worldObjects()){if(o.type==='enemy'&&!c?.world?.enemies[o.id]?.alive)continue;if(!['npc','enemy','resource'].includes(o.type))continue;const p=objectCenter(o);ctx.fillStyle=o.type==='enemy'?'#a9534f':o.type==='npc'?'#e0c667':prop(o,'resource')==='river_dace'?'#8dc4cf':'#91b36f';ctx.beginPath();ctx.arc(p.x*sx,p.y*sy,2.1*dpr,0,Math.PI*2);ctx.fill()}for(const d of c?.world?.drops||[]){ctx.fillStyle='#f0cf63';ctx.fillRect(d.x*sx-1.5*dpr,d.y*sy-1.5*dpr,3*dpr,3*dpr)}if(c){ctx.fillStyle='#fff0a2';ctx.strokeStyle='#2e2720';ctx.lineWidth=1.5*dpr;ctx.beginPath();ctx.arc(c.position.x*sx,c.position.y*sy,4*dpr,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function worldPointer(e){if(!APP.worldReady)return;APP.canvas.focus({preventScroll:true});const r=APP.canvas.getBoundingClientRect(),wx=APP.camera.x+(e.clientX-r.left)*(APP.canvas._cssW/r.width),wy=APP.camera.y+(e.clientY-r.top)*(APP.canvas._cssH/r.height),o=pickObject(wx,wy);if(o){APP.selectedObjectId=o.id;const ctr=objectCenter(o),c=current();if(dist(c.position.x,c.position.y,ctr.x,ctr.y)<110){interactObject(o)}else{APP.moveTarget={x:ctr.x,y:ctr.y};APP.pendingInteraction=o.id}}else{APP.selectedObjectId=null;APP.pendingInteraction=null;APP.moveTarget={x:wx,y:wy};APP.combat.enemyId=null;updateHud()}}
function pickObject(x,y){const c=current(),now=Date.now();for(const d of [...(c.world.drops||[])].reverse())if(dist(x,y,d.x,d.y)<34)return d;const objs=[...worldObjects()].reverse();for(const o of objs){if(o.type==='spawn'||o.type==='building')continue;if(o.type==='enemy'&&!c.world.enemies[o.id]?.alive)continue;if(o.type==='resource'&&c.world.resources[o.id]?.readyAt>now)continue;const ctr=objectCenter(o);if(dist(x,y,ctr.x,ctr.y)<38)return o}return null}
function interactObject(o){if(!o)return;APP.selectedObjectId=o.id;if(o.type==='drop')pickupDrop(o);else if(o.type==='npc')interactNpc(prop(o,'kind'),o);else if(o.type==='resource')gatherResource(o);else if(o.type==='enemy')startCombat(o);else if(o.type==='landmark')toast(o.name)}
function interactNpc(kind,o){APP.combat.enemyId=null;if(kind==='guildmaster')guildDialogue(o);else if(kind==='blacksmith')blacksmithDialogue(o);else if(kind==='merchant')merchantDialogue(o);else if(kind==='apothecary')apothecaryDialogue(o);else if(kind==='innkeeper')innkeeperDialogue(o)}
function guildDialogue(o){const st=questState('first_commission'),prog=questProgress('first_commission');let extra='';if(st==='available')extra=`<button class="game-btn gold" data-accept-quest="first_commission">Accept “A Paw on the Roads”</button>`;else if(st==='active'&&prog.complete)extra=`<button class="game-btn gold" data-claim-quest="first_commission">Turn in commission</button>`;else if(st==='active')extra=`<button class="game-btn dark" disabled>Progress: ${prog.text}</button>`;else extra=`<button class="game-btn dark" disabled>Commission completed</button>`;modal('Guildmaster Luca',`<div class="dialogue-speaker"><img src="assets/world/portrait_orange.png" alt="Guildmaster Luca"><div><span class="caps">GILDED PAW GUILD</span><strong>Guildmaster Luca</strong></div></div><p>“Port Felin has more work than paws. The south road needs clearing, and Saffron keeps asking for rosemary.”</p><div class="dialogue-options">${extra}<button class="game-btn dark" data-close3>Farewell</button></div>`);const a=modalLayer.querySelector('[data-accept-quest]');if(a)a.addEventListener('click',()=>acceptQuest('first_commission'));const q=modalLayer.querySelector('[data-claim-quest]');if(q)q.addEventListener('click',()=>claimQuest('first_commission'));modalLayer.querySelector('[data-close3]').addEventListener('click',closeModal)}
function blacksmithDialogue(){const c=current(),canRapier=countItem('iron_ore')>=3&&countItem('oak_log')>=1,canDoublet=countItem('reed')>=3;modal('Bia Ironpaw — Smith & Armorer',`<p>“Bring me material, not excuses. A good blade is a conversation that ends quickly.”</p><div class="shop-row"><div class="icon">⚔</div><div class="copy"><strong>Iron Rapier</strong><small>3 Iron Ore + 1 Oak Log • Smithing XP</small></div><button class="game-btn" data-craft="iron_rapier" ${canRapier?'':'disabled'}>Forge</button></div><div class="shop-row"><div class="icon">🧥</div><div class="copy"><strong>Padded Doublet</strong><small>3 River Reed • Tailoring XP</small></div><button class="game-btn" data-craft="padded_doublet" ${canDoublet?'':'disabled'}>Make</button></div>`);modalLayer.querySelectorAll('[data-craft]').forEach(b=>b.addEventListener('click',()=>craftItem(b.dataset.craft)))}
function merchantDialogue(){modal('Neri — Mercato Stall',`<p>“Fresh bread, road tonics, no questions about where you got those coins.”</p><div class="shop-row"><div class="icon">🥖</div><div class="copy"><strong>Brown Bread</strong><small>Restores 8 health</small></div><button class="game-btn" data-buy="bread" data-price="3">3 ◈</button></div><div class="shop-row"><div class="icon">🧪</div><div class="copy"><strong>Red Tonic</strong><small>Restores 20 health</small></div><button class="game-btn" data-buy="healing_tonic" data-price="12">12 ◈</button></div>`);modalLayer.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>buyItem(b.dataset.buy,Number(b.dataset.price))))}
function apothecaryDialogue(){const can=countItem('rosemary')>=2&&countItem('grape')>=1;modal('Saffron — Apothecary',`<p>“A little bitter leaf, a little grape, and no, I will not tell you what makes it red.”</p><div class="shop-row"><div class="icon">🧪</div><div class="copy"><strong>Brew Red Tonic</strong><small>2 Rosemary + 1 Black Grape • Alchemy XP</small></div><button class="game-btn teal" data-brew ${can?'':'disabled'}>Brew</button></div>`);const brew=modalLayer.querySelector('[data-brew]');if(brew)brew.addEventListener('click',()=>{removeItem('rosemary',2);removeItem('grape',1);addItem('healing_tonic',1);const c=current();c.counters.crafted.healing_tonic=(c.counters.crafted.healing_tonic||0)+1;addSkillXp('alchemy',18);addPlayerXp(5);playSfx('gather',.5);saveCharacter();toast('Brewed a Red Tonic.');closeModal();renderPanel()})}
function innkeeperDialogue(){const st=questState('river_supper'),prog=questProgress('river_supper'),raw=countItem('river_dace');let quest='';if(st==='available')quest=`<button class="game-btn gold" data-accept-supper>Accept “A Proper Supper”</button>`;else if(st==='active'&&prog.complete)quest=`<button class="game-btn gold" data-claim-supper>Serve Mina the supper</button>`;else if(st==='active')quest=`<button class="game-btn dark" disabled>Progress: ${prog.text}</button>`;modal('Mina Whiskerpot — Warm Saucer',`<p>“A full belly makes a steadier sword paw. If you catch anything silver in the river, I can show you what a proper pan does to it.”</p>${quest}<div class="shop-row"><div class="icon">🍢</div><div class="copy"><strong>Grill Silver Dace</strong><small>1 fresh Silver Dace • Cooking XP</small></div><button class="game-btn teal" data-cook-one ${raw?'':'disabled'}>Cook one</button></div>${raw>1?`<div class="shop-row"><div class="icon">🔥</div><div class="copy"><strong>Cook all ${raw}</strong><small>Batch cooking</small></div><button class="game-btn" data-cook-all>Cook all</button></div>`:''}<div class="dialogue-options"><button class="game-btn dark" data-rest>Rent a room until morning — 5 ◈</button></div>`);const a=modalLayer.querySelector('[data-accept-supper]');if(a)a.addEventListener('click',()=>acceptQuest('river_supper'));const q=modalLayer.querySelector('[data-claim-supper]');if(q)q.addEventListener('click',()=>claimQuest('river_supper'));const one=modalLayer.querySelector('[data-cook-one]');if(one)one.addEventListener('click',()=>cookFish(1));const all=modalLayer.querySelector('[data-cook-all]');if(all)all.addEventListener('click',()=>cookFish(raw));modalLayer.querySelector('[data-rest]').addEventListener('click',restAtInn)}
function restAtInn(){const c=current();if(c.coins<5){toast('You need 5 crowns for a room.');return}c.coins-=5;c.hp=c.maxHp;c.world.timeMinutes=420;saveCharacter();closeModal();toast('You sleep until seven bells. Health restored.');updateHud()}
function buyItem(item,price){const c=current();if(c.coins<price){toast('Not enough crowns.');return}c.coins-=price;addItem(item,1);playSfx('coin',.55);saveCharacter();toast(`Bought ${ITEMS[item].name}.`);updateHud();renderPanel()}
function craftItem(item){if(item==='iron_rapier'){if(countItem('iron_ore')<3||countItem('oak_log')<1)return;removeItem('iron_ore',3);removeItem('oak_log',1);addItem(item,1);addSkillXp('smithing',24);addSkillXp('crafting',10);addPlayerXp(8)}else if(item==='padded_doublet'){if(countItem('reed')<3)return;removeItem('reed',3);addItem(item,1);addSkillXp('tailoring',24);addSkillXp('crafting',10);addPlayerXp(8)}playSfx('gather',.6);saveCharacter();closeModal();toast(`Created ${ITEMS[item].name}.`);renderPanel()}
function gatherResource(o){const c=current(),rs=c.world.resources[o.id];if(rs.readyAt>Date.now()){toast('That resource is recovering.');return}const kind=prop(o,'resource');let item=kind,skill='foraging',xp=8,amount=1,cooldown=3500;if(kind==='oak_log'){skill='woodcutting';xp=10}else if(kind==='iron_ore'){skill='mining';xp=11}else if(kind==='river_dace'){skill='fishing';xp=12;cooldown=4800}else if(kind==='reed'||kind==='grape'||kind==='rosemary'){skill='foraging';xp=8}if(Math.random()<Math.min(.35,c.skills[skill].level*.035))amount++;addItem(item,amount);c.counters.gathered[item]=(c.counters.gathered[item]||0)+amount;rs.readyAt=Date.now()+cooldown;addSkillXp(skill,xp);addPlayerXp(3);const ctr=objectCenter(o),fish=kind==='river_dace';addBurst(ctr.x,ctr.y-12,fish?'#8fc7d2':'#b9c77b',8);addFloater(ctr.x,ctr.y-34,`+${amount} ${ITEMS[item].name}`,fish?'#b9e2eb':'#d9e7a5');playSfx(fish?'fish_splash':'gather',.72);saveCharacter();APP.log=fish?`Caught ${amount} × ${ITEMS[item].name}.`:`Gathered ${amount} × ${ITEMS[item].name}.`;toast(APP.log);renderPanel()}
function startCombat(o){const c=current(),ws=c.world.enemies[o.id];if(!ws?.alive)return;APP.combat.enemyId=o.id;APP.selectedObjectId=o.id;APP.log=`Targeting ${o.name}. Move into range to attack.`;const ctr=objectCenter(o);if(dist(c.position.x,c.position.y,ctr.x,ctr.y)>86){APP.moveTarget={x:ctr.x,y:ctr.y};APP.pendingInteraction=null}updateHud()}
function updateCombat(now){const c=current(),id=APP.combat.enemyId;if(!id)return;const o=objectById(id),ws=o&&c.world.enemies[id];if(!o||!ws?.alive){APP.combat.enemyId=null;return}const ctr=objectCenter(o),range=dist(c.position.x,c.position.y,ctr.x,ctr.y);if(range>86){if(APP.moveTarget)APP.moveTarget={x:ctr.x,y:ctr.y};return}if(now-APP.combat.lastPlayerHit>1000){APP.combat.lastPlayerHit=now;playerStrike(false)}if(ws.alive&&now-APP.combat.lastEnemyHit>1450){APP.combat.lastEnemyHit=now;enemyStrike(o)}}
function playerStrike(flourish){const c=current(),id=APP.combat.enemyId,o=objectById(id),ws=o&&c.world.enemies[id];if(!o||!ws?.alive)return;const e=ENEMIES[prop(o,'enemy')],weapon=ITEMS[c.equipment.weapon]||{attack:0};const base=2+c.skills.fencing.level*.8+(weapon.attack||0),dmg=Math.max(1,Math.round(base*(.8+Math.random()*.45)*(flourish?1.65:1)-e.defense*.35));ws.hp-=dmg;const ctr=objectCenter(o);addFloater(ctr.x,ctr.y-48,`-${dmg}`,flourish?'#ffe08b':'#ffffff');addBurst(ctr.x,ctr.y-8,flourish?'#f5cf61':'#e7e0c9',flourish?10:5);playSfx('sword_hit',flourish?1:.75);addSkillXp('fencing',flourish?5:3);APP.log=`You hit ${e.name} for ${dmg}.`;if(ws.hp<=0)defeatEnemy(o);saveCharacterThrottled();updateHud()}
function enemyStrike(o){const c=current(),e=ENEMIES[prop(o,'enemy')],armor=ITEMS[c.equipment.body]||{defense:0},dmg=Math.max(1,Math.round(e.attack*(.75+Math.random()*.5)-(armor.defense||0)*.45-c.skills.defense.level*.15));c.hp-=dmg;addFloater(c.position.x,c.position.y-52,`-${dmg}`,'#ff9a8f');addBurst(c.position.x,c.position.y-8,'#c76c62',5);playSfx('hurt',.75);addSkillXp('defense',2);APP.log=`${e.name} hits you for ${dmg}.`;if(c.hp<=0)playerDefeated();saveCharacter();updateHud()}
function defeatEnemy(o){const c=current(),kind=prop(o,'enemy'),e=ENEMIES[kind],ws=c.world.enemies[o.id];ws.alive=false;ws.hp=0;ws.respawnAt=Date.now()+30000;c.counters.kills[kind]=(c.counters.kills[kind]||0)+1;const coins=Math.floor(e.coins[0]+Math.random()*(e.coins[1]-e.coins[0]+1)),items={};for(const[item,chance]of e.loot)if(Math.random()<chance)items[item]=(items[item]||0)+1;addPlayerXp(e.xp);const ctr=objectCenter(o);spawnDrop(ctr.x+18,ctr.y+8,coins,items);addFloater(ctr.x,ctr.y-60,`+${e.xp} XP`,'#9ee6ce');addFloater(ctr.x,ctr.y-42,'Loot dropped','#f6d66d');APP.combat.enemyId=null;APP.log=`Defeated ${e.name}. +${e.xp} XP. Loot is on the ground.`;toast(APP.log);saveCharacter();renderPanel();updateHud()}
function updateEnemyRespawns(now){const c=current();for(const o of worldObjects().filter(x=>x.type==='enemy')){const ws=c.world.enemies[o.id],kind=prop(o,'enemy');if(ws&&!ws.alive&&ws.respawnAt<=Date.now()){ws.alive=true;ws.hp=ENEMIES[kind].maxHp;ws.respawnAt=0}}}
function playerDefeated(){const c=current(),lost=Math.min(c.coins,Math.floor(c.coins*.1));c.coins-=lost;c.hp=c.maxHp;c.position={x:346,y:670};APP.moveTarget=null;APP.pendingInteraction=null;APP.combat.enemyId=null;APP.log=`You wake at the Warm Saucer. Lost ${lost} crowns.`;toast(APP.log)}
function useHotbar(action){const c=current();if(action==='attack'){if(APP.combat.enemyId)playerStrike(false);else toast('Tap an enemy to target it.')}else if(action==='flourish'){if(!APP.combat.enemyId){toast('Target an enemy first.');return}const now=Date.now();if(now<APP.combat.flourishReadyAt){toast('Flourish is still recovering.');return}APP.combat.flourishReadyAt=now+5000;playerStrike(true)}else if(action==='tonic')useItem('healing_tonic');else if(action==='bread')useItem('bread');else if(action==='interact'){const o=nearestObject(85);if(o)interactObject(o);else toast('Nothing nearby to interact with.')}}
function nearestObject(maxD){const c=current();let best=null,bd=maxD;for(const o of [...worldObjects(),...(c.world.drops||[])]){if(['spawn','building'].includes(o.type))continue;if(o.type==='enemy'&&!c.world.enemies[o.id]?.alive)continue;const p=objectCenter(o),d=dist(c.position.x,c.position.y,p.x,p.y);if(d<bd){best=o;bd=d}}return best}
function useItem(item){const c=current(),it=ITEMS[item];if(countItem(item)<1){toast(`No ${it.name}.`);return}if(it.use==='heal'){if(c.hp>=c.maxHp){toast('You are already at full health.');return}removeItem(item,1);c.hp=Math.min(c.maxHp,c.hp+it.amount);saveCharacter();toast(`${it.name}: +${it.amount} health.`);updateHud();renderPanel()}}
function addItem(k,n=1){const c=current();c.inventory[k]=(c.inventory[k]||0)+n} function removeItem(k,n=1){const c=current();c.inventory[k]=Math.max(0,(c.inventory[k]||0)-n);if(c.inventory[k]===0)delete c.inventory[k]} function countItem(k){return current()?.inventory[k]||0}
function addPlayerXp(n){const c=current();c.xp+=n;while(c.xp>=xpNeed(c.level)){c.xp-=xpNeed(c.level);c.level++;c.maxHp+=4;c.hp=c.maxHp;playSfx('level_up',.8);toast(`Adventure level ${c.level}! Maximum health increased.`)}}
function addSkillXp(skill,n){const c=current(),s=c.skills[skill];s.xp+=n;while(s.xp>=skillNeed(s.level)){s.xp-=skillNeed(s.level);s.level++;playSfx('level_up',.55);toast(`${SKILL_NAMES[skill]} reached level ${s.level}.`)}}
function questProgress(id){const c=current(),q=QUESTS[id];let done=0,total=0,parts=[];for(const[kind,key,need]of q.requirements){const v=c.counters[kind]?.[key]||0;done+=Math.min(v,need);total+=need;parts.push(`${Math.min(v,need)}/${need} ${key.replaceAll('_',' ')}`)}return{complete:done>=total,pct:total?done/total:1,text:parts.join(' • ')}}
function claimQuest(id){const c=current(),q=QUESTS[id],p=questProgress(id);if(questState(id)!=='active'||!p.complete)return;const r=q.reward;c.coins+=r.coins;addPlayerXp(r.xp);if(r.item)addItem(r.item[0],r.item[1]);c.quests[id]='claimed';unlockQuests();playSfx('quest',.8);saveCharacter();closeModal();toast(`Quest complete: ${q.title}. +${r.coins} crowns, +${r.xp} XP.`);renderPanel();updateHud()}
function renderPanel(){const body=document.getElementById('panelBody');if(!body)return;const c=current();if(APP.panelTab==='inventory'){const entries=Object.entries(c.inventory);body.innerHTML=`<div class="panel-title">Inventory</div><div class="inv-grid">${entries.length?entries.map(([k,n])=>{const i=ITEMS[k]||{name:k,icon:'•'};return`<button class="inv-slot" data-inv="${k}" title="${escapeHtml(i.name)}">${i.icon}<span class="item-name">${escapeHtml(i.name)}</span>${n>1?`<small>${n}</small>`:''}</button>`}).join(''):'<p class="small muted">Your pack is empty.</p>'}</div>`;body.querySelectorAll('[data-inv]').forEach(b=>b.addEventListener('click',()=>inventoryItemModal(b.dataset.inv)))}else if(APP.panelTab==='skills'){body.innerHTML=`<div class="panel-title">Skills • total ${Object.values(c.skills).reduce((s,v)=>s+v.level,0)}</div><div class="skill-list">${Object.entries(SKILL_NAMES).map(([k,n])=>{const s=c.skills[k];return`<div class="skill-item"><strong>${n}</strong><span>${s.level}</span><small>${s.xp}/${skillNeed(s.level)} XP to next level</small></div>`}).join('')}</div>`}else if(APP.panelTab==='quests'){const visible=Object.entries(QUESTS).filter(([id])=>questState(id)!=='locked');body.innerHTML=`<div class="panel-title">Quest Journal</div>${visible.map(([id,q])=>{const st=questState(id),p=questProgress(id);return`<div class="quest-item ${st==='active'&&p.complete?'complete':''}"><strong>${q.title}</strong><p>${q.text}</p><p>${st==='available'?'Not accepted':st==='claimed'?'Completed':p.text}</p></div>`}).join('')||'<p class="small muted">No known quests.</p>'}`}else{body.innerHTML=`<div class="panel-title">Equipment</div><div class="equip-list"><div class="equip-slot"><span>Weapon</span><strong>${c.equipment.weapon?ITEMS[c.equipment.weapon].name:'Empty'}</strong></div><div class="equip-slot"><span>Body</span><strong>${c.equipment.body?ITEMS[c.equipment.body].name:'Empty'}</strong></div></div>`}}
function inventoryItemModal(k){const c=current(),i=ITEMS[k];if(!i)return;const equipped=c.equipment.weapon===k||c.equipment.body===k;let actions='';if(i.use)actions+=`<button class="game-btn teal" data-use-inv="${k}">Use</button>`;if(i.attack!=null||i.defense!=null)actions+=`<button class="game-btn gold" data-equip="${k}" ${equipped?'disabled':''}>${equipped?'Equipped':'Equip'}</button>`;modal(i.name,`<p style="font-size:36px;margin:0 0 8px">${i.icon}</p><p>${i.desc}</p><p><strong>Quantity:</strong> ${countItem(k)} ${i.attack!=null?`• Attack +${i.attack}`:''}${i.defense!=null?`• Defense +${i.defense}`:''}</p><div class="form-actions">${actions}</div>`);const u=modalLayer.querySelector('[data-use-inv]');if(u)u.addEventListener('click',()=>{useItem(k);closeModal()});const e=modalLayer.querySelector('[data-equip]');if(e)e.addEventListener('click',()=>equipItem(k))}
function equipItem(k){const c=current(),i=ITEMS[k];if(i.attack!=null)c.equipment.weapon=k;else if(i.defense!=null)c.equipment.body=k;saveCharacter();closeModal();toast(`Equipped ${i.name}.`);renderPanel()}
function updateHud(){const c=current();if(!c)return;const h=document.getElementById('hpBar'),x=document.getElementById('xpBar'),coin=document.getElementById('coinCount');if(h)h.style.width=`${clamp(c.hp/c.maxHp*100,0,100)}%`;if(x)x.style.width=`${clamp(c.xp/xpNeed(c.level)*100,0,100)}%`;if(coin)coin.textContent=c.coins;updateWorldClock();const log=document.getElementById('combatLog');if(log)log.textContent=APP.log}
function drawTargetUI(){const f=document.getElementById('targetFloat'),c=current(),id=APP.combat.enemyId;if(!f)return;if(!id){f.classList.remove('show');return}const o=objectById(id),ws=o&&c.world.enemies[id];if(!o||!ws?.alive){f.classList.remove('show');return}const e=ENEMIES[prop(o,'enemy')];f.classList.add('show');document.getElementById('targetName').textContent=e.name;document.getElementById('targetHp').style.width=`${clamp(ws.hp/e.maxHp*100,0,100)}%`}
function openGameMenu(){saveCharacter();modal('Game Menu',`<p><strong>${escapeHtml(current().name)}</strong> is saved automatically.</p><div class="dialogue-options"><button class="game-btn" data-resume>Resume</button><button class="game-btn teal" data-characters>Character Select</button><button class="game-btn dark" data-title>Return to Title</button></div>`);modalLayer.querySelector('[data-resume]').addEventListener('click',closeModal);modalLayer.querySelector('[data-characters]').addEventListener('click',()=>{saveCharacter();go('select')});modalLayer.querySelector('[data-title]').addEventListener('click',()=>{saveCharacter();go('menu')})}
function keyDown(e){if(APP.screen!=='game')return;if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();APP.keys.add(k)}if(k==='1')useHotbar('attack');if(k==='2')useHotbar('flourish');if(k==='3')useHotbar('tonic');if(k==='4')useHotbar('bread');if(k==='5'||k==='e')useHotbar('interact');if(k==='escape')openGameMenu()}
function keyUp(e){APP.keys.delete(e.key.toLowerCase())}
document.addEventListener('pointerup',e=>{if(e.target.closest?.('button'))playSfx('ui_click',.3)});document.addEventListener('visibilitychange',()=>{if(!AUDIO.ready)return;if(document.hidden){AUDIO.music?.pause();AUDIO.ambience?.pause()}else if(AUDIO.unlocked&&!APP.settings.mute){AUDIO.music?.play().catch(()=>{});AUDIO.ambience?.play().catch(()=>{})}});window.addEventListener('pointerdown',unlockAudio,{once:true,passive:true});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();APP.installPrompt=e;if(APP.screen==='menu')renderMenu()});window.addEventListener('appinstalled',()=>{APP.installPrompt=null;toast('Paws & Plumes installed.')});
window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('resize',()=>{if(APP.screen==='game')resizeWorld()});window.addEventListener('beforeunload',saveCharacter);
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',async()=>{try{APP.swRegistration=await navigator.serviceWorker.register('sw.js');APP.swRegistration.update();if(APP.swRegistration.waiting)toast('A newer app build is ready. Reload to use it.');APP.swRegistration.addEventListener('updatefound',()=>{const w=APP.swRegistration.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('App update downloaded. Reload when convenient.')})})}catch(e){console.warn('Service worker registration failed',e)}});
go('menu');
})();
